// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics.sql

package sqlc

import (
	"context"
)

const analyticsByAsset = `-- name: AnalyticsByAsset :many
SELECT
    asset,
    COUNT(*) AS total_trades,
    COUNT(CASE WHEN state = 'closed' THEN 1 END) AS closed_trades,
    COALESCE(SUM(price_pnl), 0) AS total_price_pnl,
    COALESCE(SUM(funding_pnl), 0) AS total_funding_pnl,
    COALESCE(SUM(total_pnl), 0) AS total_pnl,
    COALESCE(SUM(CASE WHEN state = 'closed' THEN realized_pnl END), 0) AS total_realized_pnl,
    COALESCE(SUM(CASE WHEN state IN ('open', 'degraded') THEN total_pnl END), 0) AS total_unrealized_pnl,
    COALESCE(AVG(CASE WHEN state = 'closed' THEN hold_hours END), 0) AS avg_hold_hours,
    COALESCE(AVG(CASE WHEN state = 'closed' THEN est_break_even_hours END), 0) AS avg_est_break_even_hours,
    COUNT(CASE WHEN state = 'closed' AND break_even_reached = 1 THEN 1 END) AS break_even_reached_count,
    COUNT(CASE WHEN state = 'closed' AND break_even_reached = 0 THEN 1 END) AS break_even_not_reached_count,
    COUNT(CASE WHEN state = 'closed' AND realized_pnl > 0 THEN 1 END) AS profitable_trades
FROM paper_positions
WHERE asset != ''
GROUP BY asset
ORDER BY total_pnl DESC
`

type AnalyticsByAssetRow struct {
	Asset                    string
	TotalTrades              int64
	ClosedTrades             int64
	TotalPricePnl            interface{}
	TotalFundingPnl          interface{}
	TotalPnl                 interface{}
	TotalRealizedPnl         interface{}
	TotalUnrealizedPnl       interface{}
	AvgHoldHours             interface{}
	AvgEstBreakEvenHours     interface{}
	BreakEvenReachedCount    int64
	BreakEvenNotReachedCount int64
	ProfitableTrades         int64
}

func (q *Queries) AnalyticsByAsset(ctx context.Context) ([]AnalyticsByAssetRow, error) {
	rows, err := q.db.QueryContext(ctx, analyticsByAsset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnalyticsByAssetRow
	for rows.Next() {
		var i AnalyticsByAssetRow
		if err := rows.Scan(
			&i.Asset,
			&i.TotalTrades,
			&i.ClosedTrades,
			&i.TotalPricePnl,
			&i.TotalFundingPnl,
			&i.TotalPnl,
			&i.TotalRealizedPnl,
			&i.TotalUnrealizedPnl,
			&i.AvgHoldHours,
			&i.AvgEstBreakEvenHours,
			&i.BreakEvenReachedCount,
			&i.BreakEvenNotReachedCount,
			&i.ProfitableTrades,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsByCloseReason = `-- name: AnalyticsByCloseReason :many
SELECT
    close_reason,
    COUNT(*) AS total_trades,
    COALESCE(SUM(price_pnl), 0) AS total_price_pnl,
    COALESCE(SUM(funding_pnl), 0) AS total_funding_pnl,
    COALESCE(SUM(realized_pnl), 0) AS total_realized_pnl,
    COALESCE(AVG(hold_hours), 0) AS avg_hold_hours,
    COUNT(CASE WHEN realized_pnl > 0 THEN 1 END) AS profitable_trades
FROM paper_positions
WHERE state = 'closed' AND close_reason != ''
GROUP BY close_reason
ORDER BY total_trades DESC
`

type AnalyticsByCloseReasonRow struct {
	CloseReason      string
	TotalTrades      int64
	TotalPricePnl    interface{}
	TotalFundingPnl  interface{}
	TotalRealizedPnl interface{}
	AvgHoldHours     interface{}
	ProfitableTrades int64
}

func (q *Queries) AnalyticsByCloseReason(ctx context.Context) ([]AnalyticsByCloseReasonRow, error) {
	rows, err := q.db.QueryContext(ctx, analyticsByCloseReason)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnalyticsByCloseReasonRow
	for rows.Next() {
		var i AnalyticsByCloseReasonRow
		if err := rows.Scan(
			&i.CloseReason,
			&i.TotalTrades,
			&i.TotalPricePnl,
			&i.TotalFundingPnl,
			&i.TotalRealizedPnl,
			&i.AvgHoldHours,
			&i.ProfitableTrades,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsByRiskTier = `-- name: AnalyticsByRiskTier :many
SELECT
    risk_tier,
    COUNT(*) AS total_trades,
    COUNT(CASE WHEN state = 'closed' THEN 1 END) AS closed_trades,
    COALESCE(SUM(price_pnl), 0) AS total_price_pnl,
    COALESCE(SUM(funding_pnl), 0) AS total_funding_pnl,
    COALESCE(SUM(total_pnl), 0) AS total_pnl,
    COALESCE(SUM(CASE WHEN state = 'closed' THEN realized_pnl END), 0) AS total_realized_pnl,
    COALESCE(AVG(CASE WHEN state = 'closed' THEN hold_hours END), 0) AS avg_hold_hours,
    COUNT(CASE WHEN state = 'closed' AND break_even_reached = 1 THEN 1 END) AS break_even_reached_count,
    COUNT(CASE WHEN state = 'closed' AND realized_pnl > 0 THEN 1 END) AS profitable_trades
FROM paper_positions
WHERE risk_tier != ''
GROUP BY risk_tier
ORDER BY risk_tier
`

type AnalyticsByRiskTierRow struct {
	RiskTier              string
	TotalTrades           int64
	ClosedTrades          int64
	TotalPricePnl         interface{}
	TotalFundingPnl       interface{}
	TotalPnl              interface{}
	TotalRealizedPnl      interface{}
	AvgHoldHours          interface{}
	BreakEvenReachedCount int64
	ProfitableTrades      int64
}

func (q *Queries) AnalyticsByRiskTier(ctx context.Context) ([]AnalyticsByRiskTierRow, error) {
	rows, err := q.db.QueryContext(ctx, analyticsByRiskTier)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnalyticsByRiskTierRow
	for rows.Next() {
		var i AnalyticsByRiskTierRow
		if err := rows.Scan(
			&i.RiskTier,
			&i.TotalTrades,
			&i.ClosedTrades,
			&i.TotalPricePnl,
			&i.TotalFundingPnl,
			&i.TotalPnl,
			&i.TotalRealizedPnl,
			&i.AvgHoldHours,
			&i.BreakEvenReachedCount,
			&i.ProfitableTrades,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsSummary = `-- name: AnalyticsSummary :one
SELECT
    COUNT(*) AS total_trades,
    COUNT(CASE WHEN state = 'closed' THEN 1 END) AS closed_trades,
    COUNT(CASE WHEN state IN ('open', 'degraded') THEN 1 END) AS open_trades,
    COUNT(CASE WHEN state = 'failed' THEN 1 END) AS failed_trades,
    COALESCE(SUM(price_pnl), 0) AS total_price_pnl,
    COALESCE(SUM(funding_pnl), 0) AS total_funding_pnl,
    COALESCE(SUM(total_pnl), 0) AS total_pnl,
    COALESCE(SUM(CASE WHEN state = 'closed' THEN realized_pnl END), 0) AS total_realized_pnl,
    COALESCE(SUM(CASE WHEN state IN ('open', 'degraded') THEN total_pnl END), 0) AS total_unrealized_pnl,
    COALESCE(AVG(CASE WHEN state = 'closed' THEN hold_hours END), 0) AS avg_hold_hours,
    COALESCE(AVG(CASE WHEN state = 'closed' THEN est_break_even_hours END), 0) AS avg_est_break_even_hours,
    COUNT(CASE WHEN state = 'closed' AND break_even_reached = 1 THEN 1 END) AS break_even_reached_count,
    COUNT(CASE WHEN state = 'closed' AND break_even_reached = 0 THEN 1 END) AS break_even_not_reached_count,
    COUNT(CASE WHEN state = 'closed' AND realized_pnl > 0 THEN 1 END) AS profitable_trades,
    COUNT(CASE WHEN state = 'closed' AND realized_pnl <= 0 THEN 1 END) AS unprofitable_trades
FROM paper_positions
`

type AnalyticsSummaryRow struct {
	TotalTrades              int64
	ClosedTrades             int64
	OpenTrades               int64
	FailedTrades             int64
	TotalPricePnl            interface{}
	TotalFundingPnl          interface{}
	TotalPnl                 interface{}
	TotalRealizedPnl         interface{}
	TotalUnrealizedPnl       interface{}
	AvgHoldHours             interface{}
	AvgEstBreakEvenHours     interface{}
	BreakEvenReachedCount    int64
	BreakEvenNotReachedCount int64
	ProfitableTrades         int64
	UnprofitableTrades       int64
}

func (q *Queries) AnalyticsSummary(ctx context.Context) (AnalyticsSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, analyticsSummary)
	var i AnalyticsSummaryRow
	err := row.Scan(
		&i.TotalTrades,
		&i.ClosedTrades,
		&i.OpenTrades,
		&i.FailedTrades,
		&i.TotalPricePnl,
		&i.TotalFundingPnl,
		&i.TotalPnl,
		&i.TotalRealizedPnl,
		&i.TotalUnrealizedPnl,
		&i.AvgHoldHours,
		&i.AvgEstBreakEvenHours,
		&i.BreakEvenReachedCount,
		&i.BreakEvenNotReachedCount,
		&i.ProfitableTrades,
		&i.UnprofitableTrades,
	)
	return i, err
}
