// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: market_snapshots.sql

package sqlc

import (
	"context"
)

const getLatestSnapshot = `-- name: GetLatestSnapshot :one
SELECT id, venue, asset, market_key, mark_price, index_price, funding_rate, bid_price, ask_price, open_interest, timestamp FROM market_snapshots
WHERE venue = ? AND asset = ?
ORDER BY timestamp DESC
LIMIT 1
`

type GetLatestSnapshotParams struct {
	Venue string
	Asset string
}

func (q *Queries) GetLatestSnapshot(ctx context.Context, arg GetLatestSnapshotParams) (MarketSnapshot, error) {
	row := q.db.QueryRowContext(ctx, getLatestSnapshot, arg.Venue, arg.Asset)
	var i MarketSnapshot
	err := row.Scan(
		&i.ID,
		&i.Venue,
		&i.Asset,
		&i.MarketKey,
		&i.MarkPrice,
		&i.IndexPrice,
		&i.FundingRate,
		&i.BidPrice,
		&i.AskPrice,
		&i.OpenInterest,
		&i.Timestamp,
	)
	return i, err
}

const insertSnapshot = `-- name: InsertSnapshot :exec
INSERT INTO market_snapshots (
    venue, asset, market_key,
    mark_price, index_price, funding_rate,
    bid_price, ask_price, open_interest,
    timestamp
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertSnapshotParams struct {
	Venue        string
	Asset        string
	MarketKey    string
	MarkPrice    float64
	IndexPrice   float64
	FundingRate  float64
	BidPrice     float64
	AskPrice     float64
	OpenInterest float64
	Timestamp    string
}

func (q *Queries) InsertSnapshot(ctx context.Context, arg InsertSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, insertSnapshot,
		arg.Venue,
		arg.Asset,
		arg.MarketKey,
		arg.MarkPrice,
		arg.IndexPrice,
		arg.FundingRate,
		arg.BidPrice,
		arg.AskPrice,
		arg.OpenInterest,
		arg.Timestamp,
	)
	return err
}

const listSnapshotsByAsset = `-- name: ListSnapshotsByAsset :many
SELECT id, venue, asset, market_key, mark_price, index_price, funding_rate, bid_price, ask_price, open_interest, timestamp FROM market_snapshots
WHERE asset = ? AND timestamp >= ? AND timestamp <= ?
ORDER BY timestamp
`

type ListSnapshotsByAssetParams struct {
	Asset       string
	Timestamp   string
	Timestamp_2 string
}

func (q *Queries) ListSnapshotsByAsset(ctx context.Context, arg ListSnapshotsByAssetParams) ([]MarketSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, listSnapshotsByAsset, arg.Asset, arg.Timestamp, arg.Timestamp_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarketSnapshot
	for rows.Next() {
		var i MarketSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.Venue,
			&i.Asset,
			&i.MarketKey,
			&i.MarkPrice,
			&i.IndexPrice,
			&i.FundingRate,
			&i.BidPrice,
			&i.AskPrice,
			&i.OpenInterest,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotsByVenueAsset = `-- name: ListSnapshotsByVenueAsset :many
SELECT id, venue, asset, market_key, mark_price, index_price, funding_rate, bid_price, ask_price, open_interest, timestamp FROM market_snapshots
WHERE venue = ? AND asset = ? AND timestamp >= ? AND timestamp <= ?
ORDER BY timestamp
`

type ListSnapshotsByVenueAssetParams struct {
	Venue       string
	Asset       string
	Timestamp   string
	Timestamp_2 string
}

func (q *Queries) ListSnapshotsByVenueAsset(ctx context.Context, arg ListSnapshotsByVenueAssetParams) ([]MarketSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, listSnapshotsByVenueAsset,
		arg.Venue,
		arg.Asset,
		arg.Timestamp,
		arg.Timestamp_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarketSnapshot
	for rows.Next() {
		var i MarketSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.Venue,
			&i.Asset,
			&i.MarketKey,
			&i.MarkPrice,
			&i.IndexPrice,
			&i.FundingRate,
			&i.BidPrice,
			&i.AskPrice,
			&i.OpenInterest,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
