// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type LiveEvent struct {
	ID         int64
	PositionID string
	Event      string
	State      string
	Detail     string
	At         string
}

type LiveFill struct {
	ID              int64
	PositionID      string
	Leg             int64
	Venue           string
	Symbol          string
	Side            string
	OrderID         string
	ClientOrderID   string
	RequestedAmount float64
	FilledAmount    float64
	AvgFillPrice    float64
	FillRatio       float64
	Fee             float64
	Accepted        int64
	Filled          int64
	Error           string
	FilledAt        string
}

type LivePosition struct {
	ID               string
	PlanID           string
	OpportunityID    string
	Asset            string
	VenueA           string
	VenueB           string
	State            string
	Notional         float64
	Leverage         float64
	EntrySpread      float64
	HedgeMismatch    float64
	StartedAt        string
	OpenedAt         sql.NullString
	CompletedAt      sql.NullString
	UpdatedAt        string
	CurrentSpread    float64
	CurrentBasis     float64
	EntryBasis       float64
	BasisChange      float64
	PricePnl         float64
	FundingPnl       float64
	TotalPnl         float64
	Leg1CurrentPrice float64
	Leg2CurrentPrice float64
	Leg1LiqPrice     float64
	Leg2LiqPrice     float64
	Leg1LiqDist      float64
	Leg2LiqDist      float64
	Leg1LiqRisk      string
	Leg2LiqRisk      string
	HoldHours        float64
	MonitorAt        sql.NullString
}

type MarketSnapshot struct {
	ID           int64
	Venue        string
	Asset        string
	MarketKey    string
	MarkPrice    float64
	IndexPrice   float64
	FundingRate  float64
	BidPrice     float64
	AskPrice     float64
	OpenInterest float64
	TsUnix       int64
}

type MarketSnapshots1h struct {
	Venue      string
	Asset      string
	BucketUnix int64
	Open       float64
	High       float64
	Low        float64
	Close      float64
	FundingAvg float64
	OiAvg      float64
	BidAvg     float64
	AskAvg     float64
}

type MarketSnapshots5m struct {
	Venue      string
	Asset      string
	BucketUnix int64
	Open       float64
	High       float64
	Low        float64
	Close      float64
	FundingAvg float64
	OiAvg      float64
	BidAvg     float64
	AskAvg     float64
}

type PaperEvent struct {
	ID         int64
	PositionID string
	FromState  string
	ToState    string
	Reason     string
	At         string
}

type PaperFill struct {
	ID         int64
	PositionID string
	Leg        int64
	Venue      string
	Side       string
	TargetSize float64
	FilledSize float64
	FillPrice  float64
	Slippage   float64
	Fee        float64
	FilledAt   string
}

type PaperPosition struct {
	ID                string
	PlanID            string
	OpportunityID     string
	Asset             string
	Direction         string
	VenueA            string
	VenueB            string
	State             string
	TargetNotional    float64
	EntrySpread       float64
	HedgeMismatch     float64
	CloseReason       string
	PricePnl          float64
	FundingPnl        float64
	TotalPnl          float64
	RealizedPnl       float64
	CreatedAt         string
	OpenedAt          sql.NullString
	ClosedAt          sql.NullString
	UpdatedAt         string
	RiskTier          string
	EstBreakEvenHours float64
	BreakEvenReached  int64
	HoldHours         float64
}
