// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type PaperEvent struct {
	ID         int64
	PositionID string
	FromState  string
	ToState    string
	Reason     string
	At         string
}

type PaperFill struct {
	ID         int64
	PositionID string
	Leg        int64
	Venue      string
	Side       string
	TargetSize float64
	FilledSize float64
	FillPrice  float64
	Slippage   float64
	Fee        float64
	FilledAt   string
}

type PaperPosition struct {
	ID             string
	PlanID         string
	OpportunityID  string
	Asset          string
	Direction      string
	VenueA         string
	VenueB         string
	State          string
	TargetNotional float64
	EntrySpread    float64
	HedgeMismatch  float64
	CloseReason    string
	PricePnl       float64
	FundingPnl     float64
	TotalPnl       float64
	RealizedPnl    float64
	CreatedAt      string
	OpenedAt       sql.NullString
	ClosedAt       sql.NullString
	UpdatedAt      string
}
