// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: paper_positions.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getEventsByPosition = `-- name: GetEventsByPosition :many
SELECT id, position_id, from_state, to_state, reason, at FROM paper_events WHERE position_id = ? ORDER BY id
`

func (q *Queries) GetEventsByPosition(ctx context.Context, positionID string) ([]PaperEvent, error) {
	rows, err := q.db.QueryContext(ctx, getEventsByPosition, positionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaperEvent
	for rows.Next() {
		var i PaperEvent
		if err := rows.Scan(
			&i.ID,
			&i.PositionID,
			&i.FromState,
			&i.ToState,
			&i.Reason,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFillsByPosition = `-- name: GetFillsByPosition :many
SELECT id, position_id, leg, venue, side, target_size, filled_size, fill_price, slippage, fee, filled_at FROM paper_fills WHERE position_id = ? ORDER BY leg
`

func (q *Queries) GetFillsByPosition(ctx context.Context, positionID string) ([]PaperFill, error) {
	rows, err := q.db.QueryContext(ctx, getFillsByPosition, positionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaperFill
	for rows.Next() {
		var i PaperFill
		if err := rows.Scan(
			&i.ID,
			&i.PositionID,
			&i.Leg,
			&i.Venue,
			&i.Side,
			&i.TargetSize,
			&i.FilledSize,
			&i.FillPrice,
			&i.Slippage,
			&i.Fee,
			&i.FilledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPosition = `-- name: GetPosition :one
SELECT id, plan_id, opportunity_id, asset, direction, venue_a, venue_b, state, target_notional, entry_spread, hedge_mismatch, close_reason, price_pnl, funding_pnl, total_pnl, realized_pnl, created_at, opened_at, closed_at, updated_at FROM paper_positions WHERE id = ?
`

func (q *Queries) GetPosition(ctx context.Context, id string) (PaperPosition, error) {
	row := q.db.QueryRowContext(ctx, getPosition, id)
	var i PaperPosition
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.OpportunityID,
		&i.Asset,
		&i.Direction,
		&i.VenueA,
		&i.VenueB,
		&i.State,
		&i.TargetNotional,
		&i.EntrySpread,
		&i.HedgeMismatch,
		&i.CloseReason,
		&i.PricePnl,
		&i.FundingPnl,
		&i.TotalPnl,
		&i.RealizedPnl,
		&i.CreatedAt,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO paper_events (
    position_id, from_state, to_state, reason, at
) VALUES (?, ?, ?, ?, ?)
`

type InsertEventParams struct {
	PositionID string
	FromState  string
	ToState    string
	Reason     string
	At         string
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.ExecContext(ctx, insertEvent,
		arg.PositionID,
		arg.FromState,
		arg.ToState,
		arg.Reason,
		arg.At,
	)
	return err
}

const insertFill = `-- name: InsertFill :exec
INSERT INTO paper_fills (
    position_id, leg, venue, side,
    target_size, filled_size, fill_price,
    slippage, fee, filled_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertFillParams struct {
	PositionID string
	Leg        int64
	Venue      string
	Side       string
	TargetSize float64
	FilledSize float64
	FillPrice  float64
	Slippage   float64
	Fee        float64
	FilledAt   string
}

func (q *Queries) InsertFill(ctx context.Context, arg InsertFillParams) error {
	_, err := q.db.ExecContext(ctx, insertFill,
		arg.PositionID,
		arg.Leg,
		arg.Venue,
		arg.Side,
		arg.TargetSize,
		arg.FilledSize,
		arg.FillPrice,
		arg.Slippage,
		arg.Fee,
		arg.FilledAt,
	)
	return err
}

const insertPosition = `-- name: InsertPosition :exec
INSERT INTO paper_positions (
    id, plan_id, opportunity_id, asset, direction,
    venue_a, venue_b, state, target_notional,
    entry_spread, hedge_mismatch, close_reason,
    price_pnl, funding_pnl, total_pnl, realized_pnl,
    created_at, opened_at, closed_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?, ?
)
`

type InsertPositionParams struct {
	ID             string
	PlanID         string
	OpportunityID  string
	Asset          string
	Direction      string
	VenueA         string
	VenueB         string
	State          string
	TargetNotional float64
	EntrySpread    float64
	HedgeMismatch  float64
	CloseReason    string
	PricePnl       float64
	FundingPnl     float64
	TotalPnl       float64
	RealizedPnl    float64
	CreatedAt      string
	OpenedAt       sql.NullString
	ClosedAt       sql.NullString
	UpdatedAt      string
}

func (q *Queries) InsertPosition(ctx context.Context, arg InsertPositionParams) error {
	_, err := q.db.ExecContext(ctx, insertPosition,
		arg.ID,
		arg.PlanID,
		arg.OpportunityID,
		arg.Asset,
		arg.Direction,
		arg.VenueA,
		arg.VenueB,
		arg.State,
		arg.TargetNotional,
		arg.EntrySpread,
		arg.HedgeMismatch,
		arg.CloseReason,
		arg.PricePnl,
		arg.FundingPnl,
		arg.TotalPnl,
		arg.RealizedPnl,
		arg.CreatedAt,
		arg.OpenedAt,
		arg.ClosedAt,
		arg.UpdatedAt,
	)
	return err
}

const listOpenPositions = `-- name: ListOpenPositions :many
SELECT id, plan_id, opportunity_id, asset, direction, venue_a, venue_b, state, target_notional, entry_spread, hedge_mismatch, close_reason, price_pnl, funding_pnl, total_pnl, realized_pnl, created_at, opened_at, closed_at, updated_at FROM paper_positions WHERE state IN ('open', 'degraded') ORDER BY created_at DESC
`

func (q *Queries) ListOpenPositions(ctx context.Context) ([]PaperPosition, error) {
	rows, err := q.db.QueryContext(ctx, listOpenPositions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaperPosition
	for rows.Next() {
		var i PaperPosition
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.OpportunityID,
			&i.Asset,
			&i.Direction,
			&i.VenueA,
			&i.VenueB,
			&i.State,
			&i.TargetNotional,
			&i.EntrySpread,
			&i.HedgeMismatch,
			&i.CloseReason,
			&i.PricePnl,
			&i.FundingPnl,
			&i.TotalPnl,
			&i.RealizedPnl,
			&i.CreatedAt,
			&i.OpenedAt,
			&i.ClosedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPositions = `-- name: ListPositions :many
SELECT id, plan_id, opportunity_id, asset, direction, venue_a, venue_b, state, target_notional, entry_spread, hedge_mismatch, close_reason, price_pnl, funding_pnl, total_pnl, realized_pnl, created_at, opened_at, closed_at, updated_at FROM paper_positions ORDER BY created_at DESC
`

func (q *Queries) ListPositions(ctx context.Context) ([]PaperPosition, error) {
	rows, err := q.db.QueryContext(ctx, listPositions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaperPosition
	for rows.Next() {
		var i PaperPosition
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.OpportunityID,
			&i.Asset,
			&i.Direction,
			&i.VenueA,
			&i.VenueB,
			&i.State,
			&i.TargetNotional,
			&i.EntrySpread,
			&i.HedgeMismatch,
			&i.CloseReason,
			&i.PricePnl,
			&i.FundingPnl,
			&i.TotalPnl,
			&i.RealizedPnl,
			&i.CreatedAt,
			&i.OpenedAt,
			&i.ClosedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePosition = `-- name: UpdatePosition :exec
UPDATE paper_positions SET
    state = ?,
    entry_spread = ?,
    hedge_mismatch = ?,
    close_reason = ?,
    price_pnl = ?,
    funding_pnl = ?,
    total_pnl = ?,
    realized_pnl = ?,
    opened_at = ?,
    closed_at = ?,
    updated_at = ?
WHERE id = ?
`

type UpdatePositionParams struct {
	State         string
	EntrySpread   float64
	HedgeMismatch float64
	CloseReason   string
	PricePnl      float64
	FundingPnl    float64
	TotalPnl      float64
	RealizedPnl   float64
	OpenedAt      sql.NullString
	ClosedAt      sql.NullString
	UpdatedAt     string
	ID            string
}

func (q *Queries) UpdatePosition(ctx context.Context, arg UpdatePositionParams) error {
	_, err := q.db.ExecContext(ctx, updatePosition,
		arg.State,
		arg.EntrySpread,
		arg.HedgeMismatch,
		arg.CloseReason,
		arg.PricePnl,
		arg.FundingPnl,
		arg.TotalPnl,
		arg.RealizedPnl,
		arg.OpenedAt,
		arg.ClosedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
