// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rollups.sql

package sqlc

import (
	"context"
)

const list1hByVenueAsset = `-- name: List1hByVenueAsset :many
SELECT venue, asset, bucket_unix, open, high, low, close, funding_avg, oi_avg, bid_avg, ask_avg FROM market_snapshots_1h
WHERE venue = ? AND asset = ? AND bucket_unix >= ? AND bucket_unix <= ?
ORDER BY bucket_unix
`

type List1hByVenueAssetParams struct {
	Venue        string
	Asset        string
	BucketUnix   int64
	BucketUnix_2 int64
}

func (q *Queries) List1hByVenueAsset(ctx context.Context, arg List1hByVenueAssetParams) ([]MarketSnapshots1h, error) {
	rows, err := q.db.QueryContext(ctx, list1hByVenueAsset,
		arg.Venue,
		arg.Asset,
		arg.BucketUnix,
		arg.BucketUnix_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarketSnapshots1h
	for rows.Next() {
		var i MarketSnapshots1h
		if err := rows.Scan(
			&i.Venue,
			&i.Asset,
			&i.BucketUnix,
			&i.Open,
			&i.High,
			&i.Low,
			&i.Close,
			&i.FundingAvg,
			&i.OiAvg,
			&i.BidAvg,
			&i.AskAvg,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const list5mByVenueAsset = `-- name: List5mByVenueAsset :many
SELECT venue, asset, bucket_unix, open, high, low, close, funding_avg, oi_avg, bid_avg, ask_avg FROM market_snapshots_5m
WHERE venue = ? AND asset = ? AND bucket_unix >= ? AND bucket_unix <= ?
ORDER BY bucket_unix
`

type List5mByVenueAssetParams struct {
	Venue        string
	Asset        string
	BucketUnix   int64
	BucketUnix_2 int64
}

func (q *Queries) List5mByVenueAsset(ctx context.Context, arg List5mByVenueAssetParams) ([]MarketSnapshots5m, error) {
	rows, err := q.db.QueryContext(ctx, list5mByVenueAsset,
		arg.Venue,
		arg.Asset,
		arg.BucketUnix,
		arg.BucketUnix_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarketSnapshots5m
	for rows.Next() {
		var i MarketSnapshots5m
		if err := rows.Scan(
			&i.Venue,
			&i.Asset,
			&i.BucketUnix,
			&i.Open,
			&i.High,
			&i.Low,
			&i.Close,
			&i.FundingAvg,
			&i.OiAvg,
			&i.BidAvg,
			&i.AskAvg,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSnapshot1h = `-- name: UpsertSnapshot1h :exec
INSERT INTO market_snapshots_1h (
    venue, asset, bucket_unix,
    open, high, low, close,
    funding_avg, oi_avg, bid_avg, ask_avg
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(venue, asset, bucket_unix) DO UPDATE SET
    open        = excluded.open,
    high        = excluded.high,
    low         = excluded.low,
    close       = excluded.close,
    funding_avg = excluded.funding_avg,
    oi_avg      = excluded.oi_avg,
    bid_avg     = excluded.bid_avg,
    ask_avg     = excluded.ask_avg
`

type UpsertSnapshot1hParams struct {
	Venue      string
	Asset      string
	BucketUnix int64
	Open       float64
	High       float64
	Low        float64
	Close      float64
	FundingAvg float64
	OiAvg      float64
	BidAvg     float64
	AskAvg     float64
}

func (q *Queries) UpsertSnapshot1h(ctx context.Context, arg UpsertSnapshot1hParams) error {
	_, err := q.db.ExecContext(ctx, upsertSnapshot1h,
		arg.Venue,
		arg.Asset,
		arg.BucketUnix,
		arg.Open,
		arg.High,
		arg.Low,
		arg.Close,
		arg.FundingAvg,
		arg.OiAvg,
		arg.BidAvg,
		arg.AskAvg,
	)
	return err
}

const upsertSnapshot5m = `-- name: UpsertSnapshot5m :exec
INSERT INTO market_snapshots_5m (
    venue, asset, bucket_unix,
    open, high, low, close,
    funding_avg, oi_avg, bid_avg, ask_avg
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(venue, asset, bucket_unix) DO UPDATE SET
    open        = excluded.open,
    high        = excluded.high,
    low         = excluded.low,
    close       = excluded.close,
    funding_avg = excluded.funding_avg,
    oi_avg      = excluded.oi_avg,
    bid_avg     = excluded.bid_avg,
    ask_avg     = excluded.ask_avg
`

type UpsertSnapshot5mParams struct {
	Venue      string
	Asset      string
	BucketUnix int64
	Open       float64
	High       float64
	Low        float64
	Close      float64
	FundingAvg float64
	OiAvg      float64
	BidAvg     float64
	AskAvg     float64
}

func (q *Queries) UpsertSnapshot5m(ctx context.Context, arg UpsertSnapshot5mParams) error {
	_, err := q.db.ExecContext(ctx, upsertSnapshot5m,
		arg.Venue,
		arg.Asset,
		arg.BucketUnix,
		arg.Open,
		arg.High,
		arg.Low,
		arg.Close,
		arg.FundingAvg,
		arg.OiAvg,
		arg.BidAvg,
		arg.AskAvg,
	)
	return err
}
